FROM colmap/colmap:latest

ARG DEBIAN_FRONTEND=noninteractive
ENV TZ=Asia/Shanghai

ARG PYTHON_VERSION=3.10
RUN apt-get update -y
RUN apt-get install -y unzip wget software-properties-common
RUN add-apt-repository ppa:deadsnakes/ppa && \
    apt-get -y update && \
    apt-get install -y python${PYTHON_VERSION} && \
    apt-get install -y python${PYTHON_VERSION}-distutils
RUN wget https://bootstrap.pypa.io/get-pip.py && python${PYTHON_VERSION} get-pip.py
RUN update-alternatives --install /usr/bin/python3 python3 /usr/bin/python${PYTHON_VERSION} 1

RUN pip3 install --upgrade pip
RUN pip3 install numpy pandas scipy

RUN pip3 uninstall -y blinker || true  
RUN rm -rf /usr/local/lib/python*/site-packages/blinker*
RUN pip3 install --ignore-installed open3d
